# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import math

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(303, 417)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sub = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("-"))
        self.sub.setGeometry(QtCore.QRect(250, 80, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.sub.setFont(font)
        self.sub.setObjectName("sub")
        self.root = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("r^2"))
        self.root.setGeometry(QtCore.QRect(10, 80, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.root.setFont(font)
        self.root.setObjectName("root")
        self.per = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("%"))
        self.per.setGeometry(QtCore.QRect(70, 80, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.per.setFont(font)
        self.per.setObjectName("per")
        self.one_clear = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("c"))
        self.one_clear.setGeometry(QtCore.QRect(190, 80, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.one_clear.setFont(font)
        self.one_clear.setObjectName("one_clear")
        self.all_clear = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("C"))
        self.all_clear.setGeometry(QtCore.QRect(130, 80, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.all_clear.setFont(font)
        self.all_clear.setObjectName("all_clear")
        self.square = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("s^2"))
        self.square.setGeometry(QtCore.QRect(10, 140, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.square.setFont(font)
        self.square.setObjectName("square")
        self._7 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("7"))
        self._7.setGeometry(QtCore.QRect(70, 140, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self._7.setFont(font)
        self._7.setObjectName("_7")
        self._8 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("8"))
        self._8.setGeometry(QtCore.QRect(130, 140, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self._8.setFont(font)
        self._8.setObjectName("_8")
        self._9 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("9"))
        self._9.setGeometry(QtCore.QRect(190, 140, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self._9.setFont(font)
        self._9.setObjectName("_9")
        self.div = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("/"))
        self.div.setGeometry(QtCore.QRect(250, 140, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.div.setFont(font)
        self.div.setObjectName("div")
        self.mul = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("X"))
        self.mul.setGeometry(QtCore.QRect(250, 200, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.mul.setFont(font)
        self.mul.setObjectName("mul")
        self._6 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("6"))
        self._6.setGeometry(QtCore.QRect(190, 200, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self._6.setFont(font)
        self._6.setObjectName("_6")
        self._5 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("5"))
        self._5.setGeometry(QtCore.QRect(130, 200, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self._5.setFont(font)
        self._5.setObjectName("_5")
        self._4 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("4"))
        self._4.setGeometry(QtCore.QRect(70, 200, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self._4.setFont(font)
        self._4.setObjectName("_4")
        self.cube = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("s^3"))
        self.cube.setGeometry(QtCore.QRect(10, 200, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cube.setFont(font)
        self.cube.setObjectName("cube")
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(20, 10, 281, 61))
        self.output.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.output.setFont(font)
        self.output.setFrameShape(QtWidgets.QFrame.Box)
        self.output.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output.setObjectName("output")
        self.fact = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("!"))
        self.fact.setGeometry(QtCore.QRect(10, 260, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.fact.setFont(font)
        self.fact.setObjectName("fact")
        self._1 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("1"))
        self._1.setGeometry(QtCore.QRect(70, 260, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self._1.setFont(font)
        self._1.setObjectName("_1")
        self._2 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("2"))
        self._2.setGeometry(QtCore.QRect(130, 260, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self._2.setFont(font)
        self._2.setObjectName("_2")
        self._3 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("3"))
        self._3.setGeometry(QtCore.QRect(190, 260, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self._3.setFont(font)
        self._3.setObjectName("_3")
        self.add = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("+"))
        self.add.setGeometry(QtCore.QRect(250, 260, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.add.setFont(font)
        self.add.setObjectName("add")
        self.log = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("log()"))
        self.log.setGeometry(QtCore.QRect(10, 320, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.log.setFont(font)
        self.log.setObjectName("log")
        self._0 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("0"))
        self._0.setGeometry(QtCore.QRect(130, 320, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self._0.setFont(font)
        self._0.setObjectName("_0")
        self._00 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("00"))
        self._00.setGeometry(QtCore.QRect(70, 320, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self._00.setFont(font)
        self._00.setObjectName("_00")
        self.deci = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("."))
        self.deci.setGeometry(QtCore.QRect(190, 320, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.deci.setFont(font)
        self.deci.setObjectName("deci")
        self.equal = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press("="))
        self.equal.setGeometry(QtCore.QRect(250, 320, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.equal.setFont(font)
        self.equal.setObjectName("equal")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 303, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.sub.setText(_translate("MainWindow", "-"))
        self.root.setText(_translate("MainWindow", "√"))
        self.per.setText(_translate("MainWindow", "%"))
        self.one_clear.setText(_translate("MainWindow", "CE"))
        self.all_clear.setText(_translate("MainWindow", "AC"))
        self.square.setText(_translate("MainWindow", "(X)^2"))
        self._7.setText(_translate("MainWindow", "7"))
        self._8.setText(_translate("MainWindow", "8"))
        self._9.setText(_translate("MainWindow", "9"))
        self.div.setText(_translate("MainWindow", "\\"))
        self.mul.setText(_translate("MainWindow", "X"))
        self._6.setText(_translate("MainWindow", "6"))
        self._5.setText(_translate("MainWindow", "5"))
        self._4.setText(_translate("MainWindow", "4"))
        self.cube.setText(_translate("MainWindow", "(X)^3"))
        self.output.setText(_translate("MainWindow", "0"))
        self.fact.setText(_translate("MainWindow", "!"))
        self._1.setText(_translate("MainWindow", "1"))
        self._2.setText(_translate("MainWindow", "2"))
        self._3.setText(_translate("MainWindow", "3"))
        self.add.setText(_translate("MainWindow", "+"))
        self.log.setText(_translate("MainWindow", "log(x)"))
        self._0.setText(_translate("MainWindow", "0"))
        self._00.setText(_translate("MainWindow", "00"))
        self.deci.setText(_translate("MainWindow", "."))
        self.equal.setText(_translate("MainWindow", "="))
    def press(self,a):
        def replace():
            self.calc=self.calc.replace('X','*')
            self.calc=self.calc.replace("^3",'**3')
            self.calc=self.calc.replace("^2",'**2')

        try:
            if a=='C':
                self.calc="0"           
            elif a=="c":
                if len(self.calc)>1:
                    self.calc=self.calc[:-1]
                    if self.calc[-1]=="^":
                        self.calc=self.calc[:-1]
                else:
                    self.calc="0"
            elif a=="=":
                replace()
                self.calc=str(eval(self.calc))   
            elif a=="00" or a=="0" or self.calc=="0" :
                if self.calc !="0":
                    self.calc+=a
                elif a=="00":
                    self.calc='0'
                elif a=='s^3' or a=="s^2":
                    self.calc='0'
                elif a=="r^2":
                    self.calc="0"
                elif a in self.oppe:
                    self.calc+=a
                elif a=="log()":
                    self.calc="0"
                else:
                    self.calc=a
            elif a=='s^3' or a=="s^2":
                self.calc+=f'^{a[-1]}'
            elif a=="r^2":
                self.calc=str("{:.3f}".format((eval(self.calc)**(1/2))))
            elif a=="!":
                fa=1
                for x in range(1,int(self.calc)+1):
                    fa*=x
                self.calc=str(fa)
            elif a=="log()":
                self.calc=str("{:.5f}".format(math.log(eval(self.calc))))
            elif a=="%":
                replace()
                self.calc=str(eval(self.calc)*(1/100))
            else:
                if a in self.oppe :
                    if self.calc[-1] in self.oppe :
                        self.calc=self.calc[:-1]+a
                    else:
                        replace()
                        self.calc=str(eval(self.calc))+a 
                else:  
                    self.calc+=a
            
        except Exception as e:
            pass
            
        else:
            self.output.setText(self.calc)
    calc="0"
    oppe=("+","-","X","/")
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
